### ISSUE TITLE
Add "First Class Recorded Letters" to module

### ISSUE THREAD

**Issue by punkstar** [meanbee/royalmail#4]
Suggested by Dan on GetSatisfcation on https://getsatisfaction.com/meanbee/topics/request_1st_class_recorded_letters?utm_content=topic_link&utm_medium=email&utm_source=reply_notification.

Prices can be found at http://www.royalmail.com/delivery/business-delivery-options-uk/recorded-signed/prices

**Comment by RidRack** [comment]
Closed as implemented in 2.7.0.
