### ISSUE TITLE
UNsigned 1st Class Parcel NO longer available

### ISSUE THREAD

**Issue by drunkvegas** [meanbee/royalmail#54]
Even though it's one of the options that I have selected in the shipping methods. Unsigned First Class Parcel is no longer available as an option? I have to select SIGNED For option in order to give UK customers a shipping options.

**Comment by RidRack** [comment]
Closing as fixed in https://github.com/meanbee/royalmail/commit/c538a0239a8d16ba8a969fbe44015aae4c200e6b. Merging in now.
